uncompyle6/semantics/pysource.py

This PR fixes the decompilation of class decorators. It crashes with current master version because the handler for `classdefdeco2` is the same as for `classdef` while the structure of both nodes is slightly different.
The changes simply imply checking the node type and choose the appropriate child to consider as the `buildclass`. Also, there are some cosmetic changes so that the decorations are glued to the class definition and glued together.
You can test the changes by compiling [this Python file](https://gist.github.com/Tey/0d00c9313ab6770ff211328552d411e1#file-classdec_test-py).
**Similar changes are probably needed for Python 3 files** ([line 1142](https://github.com/rocky/python-uncompyle6/pull/15/files#diff-2f08c9a8823cc79320bcf701cf255fc9R1142)), but I don't have such a version …

Fix for class decorators

---

uncompyle6/parser.py
uncompyle6/semantics/fragments.py
uncompyle6/semantics/pysource.py
uncompyle6/show.py

I've made it so that you can pass file like objects for showast and showasm. In this case the asm and ast will be written to the file like object passed rather than sys.stdout.

Diagnostics to stream

---

Makefile
README.rst
test/Makefile
test/test_pythonlib.py
uncompyle6/bin/uncompile.py
uncompyle6/parsers/parse3.py
uncompyle6/parsers/parse36.py
uncompyle6/scanner.py
uncompyle6/scanners/scanner36.py
uncompyle6/scanners/tok.py
uncompyle6/semantics/aligner.py
uncompyle6/semantics/pysource.py
uncompyle6/verify.py

@moagstar this is not the full spec. It doesn't handle for example format specifiers and `!r`, `!a` and so on. But I did want to move forward on Python 3.6. 
If you are interested and up for it, perhaps you would finish the job?

Move forward on moagstar's Python 3.6 support 

---

pytest/test_fstring.py
uncompyle6/parsers/parse3.py
uncompyle6/semantics/pysource.py

Changed fstring decompilation so that the call to join is left intact rather than trying to reconstruct the original fstring from the various expression parts. This allows f strings with 0, 1 and multiple expressions to be decompiled. It also simplifies decompilation of conversion specifiers !s !r !

merge fstring changes from moagstar

---

uncompyle6/main.py

when use the args of "-ro  outdir inputdir", only the first file is generated, other files is covered.

fix bug : not generate all files when use "-ro"

---

uncompyle6/main.py

Reverts rocky/python-uncompyle6#78
This create a _lot_ of unnecessary output when I run "make check".

Revert "fix bug : not generate all files when use "-ro""

---

pytest/test_build_const_key_map.py
pytest/validate.py
requirements-dev.txt
uncompyle6/semantics/pysource.py

Two changes in this branch, validation arbitrary code snippet decompilation (still needs a bit of work but works ok for simple expressions) , and support for python 3.6 BUILD_CONST_KEY_MAP.

Build const key map

---

uncompyle6/parsers/parse3.py

Missed this change from my last pull request which is necessary for the correct decompilation of BUILD_CONST_KEY_MAP

fixed bug with BUILD_CONST_KEY_MAP

---

.gitignore
pytest/test_function_call.py
pytest/validate.py

I've added some basic tests which should hopefully cover the majority of the new python 3.6 bytecodes and semantic changes for function calls. The majority of these tests are currently failing so I have marked these tests as expected failures. I wanted to merge these tests separately since I'd like to try and tackle the various issues in separate branches as I get time to do so, all of these will depend on these tests.
There is also a property based test which should test the various combinations more thoroughly, this test is skipped until the others are all passing.

Property based test function call

---

uncompyle6/semantics/aligner.py
uncompyle6/semantics/fragments.py
uncompyle6/semantics/make_function.py
uncompyle6/semantics/pysource.py

The `global` statements stored in a set() when generating code. The order of multiple `global` is not fixed.
When using a decompile bot to detect code changes, this will cause false positive.
This PR is to keep multiple `global` statements in fixed order.

Keep global statements in fixed order

---

pytest/test_fjt.py
uncompyle6/scanners/scanner3.py

Python 3.6 and later in switching to word sizes reduces the potential sizes of operands.
This in turn means that there are many more EXTENDED_ARG instructions allow be able to handle operands requiring more than a byte.  
In trying to remove these and working with instructions, there will be gaps in offsets where the EXTENDED_ARG instructions have been removed. 
Right now our processing still is a mixture of the opcode array and the instruction array. 
This code is messy, but right now it's the best we can do.

Extended args handling to address 3.6+ problems

---

uncompyle6/semantics/customize36.py

As discussed in #227, for a better pythonic form we need implementing `n_call_ex_kw` for have form:
```
return testobj.testmethod(c, test='A', **extra_args)
```
instead of:
```
return testobj.testmethod(*(c,), test='A', **extra_args)
```

implements n_call_ex_kw as discussed in #227

---

uncompyle6/parsers/parse36.py
uncompyle6/parsers/parse37.py
uncompyle6/scanners/scanner3.py
uncompyle6/semantics/customize37.py
uncompyle6/semantics/pysource.py

Addresses all of problems seen in 3.7 datetime.py
See also Issue #235

Less dishonest COME_FROMs in 3.6+ code

---

uncompyle6/bin/uncompile.py
uncompyle6/main.py
uncompyle6/semantics/helper.py
uncompyle6/semantics/pysource.py

There are some issue i think, using python2.7 env to decompile python3.7 pyc results in `\n\n` docstring, which i think this is `xdis` related issue.
This is WIP.
fixes #241.

Towards supporting unicode

---

test/simple_source/bug34/08_while_if.py
uncompyle6/parsers/parse3.py
uncompyle6/semantics/consts.py
uncompyle6/semantics/pysource.py

@x0ret here is I think what remains of the if-elif-else branch with the one change to not remove 
```antlr
iflaststmtl ::= testexpr c_stmts_opt JUMP_BACK
```
and a potential test for this. 
Please review to make sure this has all of what you intend. 
The whilbugs test should be improved a little bit and then we should add it as a run test.
And I think this points out that there are possibly more bugs and more `elif` conversion possibilities.

If elif else more

---

uncompyle6/parsers/parse2.py
uncompyle6/parsers/parse3.py

`expr1024` requires `expr32`, but a `build_count` of 1024 would emit only the
`expr1024` rule and rely on luck of it being emitted somewhere else.
Emit `expr32` rule either if there is a `expr32` use or a `expr1024` use to avoid.

parsers: parse2: fix: also emit expr32 if count perfectly divisible by 1024

---

test/simple_source/looping/12_if_while_true_pass.py

There is a small typo in test/simple_source/looping/12_if_while_true_pass.py.
Should read `unnecessary` rather than `unecessary`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, unecessary -> unnecessary

---

uncompyle6/bin/uncompile.py

main calls with source_paths=None, but it needs to be iterable

'NoneType' object is not iterable with numproc > 1

---

uncompyle6/semantics/customize36.py

self.version here is a tuple, hence an exception is raised when comparing it to 3.6 which is a float

Fix version check comparison

---

uncompyle6/parsers/parse3.py
uncompyle6/parsers/parse36.py
uncompyle6/parsers/parse37base.py
uncompyle6/scanners/scanner3.py
uncompyle6/semantics/customize36.py

Use LOAD_FAST -> LOAD_ARG when it is that  (as name `.0`). 
This makes grammar clearer. Also we add a few more async rules from the 3.7 grammar.

Use LOAD_ARG in 3.6

---

uncompyle6/semantics/make_function36.py

Should fix:
```python
uncompyle6/semantics/make_function36.py", line 170, in make_function36
except (ParserError, ParserError2) as p:
NameError: name 'ParserError2' is not defined
```

Add missing ParserError2 in make_functions36

---

uncompyle6/bin/uncompile.py

Fixes:
```python
uncompyle6/bin/uncompile.py", line 201, in main_bin
mess = status_msg(do_verify, *result)
TypeError: status_msg() takes 5 positional arguments but 6 were given
```

Fix status_msg args

---

uncompyle6/parsers/parse37base.py

"expr" -> "pos_args" because it matters/matteredin https://github.com/scikit-hep/vector/pull/305#issuecomment-1387451286 . Possibly it may matter in other places as well. And "pos_args" is I suppose a little more clear than "expr".
Fixes #428

Reinstate pos_args in CALL_METHOD

---

uncompyle6/parsers/reducecheck/ifelsestmt.py

I followed your guidelines, and reworked ifelsestmt.py a bit. I just added another set of rules that is then checked for offsets, it fixed this particular issue (#437) at least. I know the tests in test/ aren't great, but at least they aren't failing :)
I ran the tests on test/stdlib/runtests.sh also (Python 2.7) but I keep getting an error, which I included in issue #439. I might look into that one also since I am working on it.

Tentative fix for issue #437.

---

uncompyle6/semantics/n_actions.py

I separated repr and str by Python version. The test is still broken, the 3.8 bytecode is being decompiled in wrong blocks, I might look into that later.

Proposed fix for the extra quotes

---

uncompyle6/semantics/customize.py
uncompyle6/semantics/customize25.py
uncompyle6/semantics/customize26_27.py
uncompyle6/semantics/customize3.py
uncompyle6/semantics/customize35.py
uncompyle6/semantics/customize36.py
uncompyle6/semantics/customize37.py
uncompyle6/semantics/customize38.py
uncompyle6/semantics/fragments.py

Do not overwrite possible previous updates to the new TABLE_R and TABLE_DIRECT dictionaries.

Use a single TABLE copy

---

uncompyle6/code_fns.py

This fixes "diassembles" to "disassembles" in `code_fns.py`

Fix typo for code_fns function docstring

---

uncompyle6/linenumbers.py

The copyright date listed in `linenumpers.py` includes the year 2818; this changes it to 2018.

Change copyright year to 2018
